name: Node package CD

inputs:
  node-auth-token:
    required: true
  node-version:
    required: false
    default: 20

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        registry-url: https://registry.npmjs.org
    - id: scripts
      run: |
        scripts=$(cat package.json | jq -c '.scripts | keys')
        echo "scripts=$scripts" >> $GITHUB_OUTPUT
      shell: bash
    - if: ${{ contains(steps.scripts.outputs.scripts, 'build') }}
      run: |
        npm ci || npm install
        npm run build
      shell: bash
    - run: npm publish --access public --no-verify
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
      shell: bash
